"""
Import sample dashboard JSON into the application's MySQL schema.

This loader inserts:
- users
- students
- semester_results

It uses the JSON generated by generate_student_db_json.py and converts
semester-level academic records into subject-level semester_results so the
dashboard queries in app.py can calculate totals, CGPA, and previous semester
averages.
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

import mysql.connector

from database_v2 import get_db_connection, get_grade, init_db
from generate_student_db_json import DEFAULT_OUTPUT, build_dataset
from seed_subjects import seed_subjects


RANDOM_SEED = 20260327


def load_dataset(path: Path) -> dict:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    dataset = build_dataset()
    path.write_text(json.dumps(dataset, indent=2), encoding="utf-8")
    return dataset


def ensure_schema_and_subjects() -> None:
    init_db()
    seed_subjects()


def ensure_student_user(cursor, roll_number: str, role_id: int) -> int:
    cursor.execute(
        """
        INSERT IGNORE INTO users (username, password_hash, role_id, is_active, is_approved)
        VALUES (%s, %s, %s, %s, %s)
        """,
        (roll_number, "123", role_id, True, True),
    )
    cursor.execute("SELECT id FROM users WHERE username = %s", (roll_number,))
    return cursor.fetchone()["id"]


def clear_existing_student_data(cursor, student_role_id: int) -> None:
    """
    Reset student-facing data while preserving admin/staff accounts.

    This is useful when we want the dashboard to reflect only the generated
    720-student sample dataset.
    """
    cursor.execute("DELETE FROM semester_results")
    cursor.execute("DELETE FROM student_marks")
    cursor.execute("DELETE FROM attendance")
    cursor.execute("DELETE FROM students")
    cursor.execute(
        "DELETE FROM users WHERE role_id = %s AND username <> %s",
        (student_role_id, "student"),
    )


def build_subject_mark(rng: random.Random, sgpa: float) -> tuple[float, float, float, str, int]:
    target_total = clamp((sgpa * 10) + rng.uniform(-7.0, 7.0), 48.0, 98.0)
    total_marks = round(target_total, 2)
    internal_marks = round(clamp((total_marks * 0.38) + rng.uniform(-2.0, 2.0), 18.0, 40.0), 2)
    external_marks = round(clamp(total_marks - internal_marks, 20.0, 60.0), 2)
    total_marks = round(internal_marks + external_marks, 2)
    grade, grade_point = get_grade(int(round(total_marks)))
    return internal_marks, external_marks, total_marks, grade, grade_point


def clamp(value: float, low: float, high: float) -> float:
    return max(low, min(high, value))


def import_dataset(path: Path, replace_existing: bool = False) -> None:
    dataset = load_dataset(path)
    ensure_schema_and_subjects()

    conn = get_db_connection()
    if not conn:
        raise RuntimeError("Could not connect to MySQL.")

    rng = random.Random(RANDOM_SEED)
    cursor = conn.cursor(dictionary=True)

    cursor.execute("SELECT id FROM roles WHERE name = 'STUDENT'")
    role_row = cursor.fetchone()
    if not role_row:
        raise RuntimeError("STUDENT role was not found after schema initialization.")
    student_role_id = role_row["id"]

    if replace_existing:
        clear_existing_student_data(cursor, student_role_id)
        conn.commit()

    cursor.execute("SELECT id, code, name FROM departments WHERE is_active = TRUE")
    departments = {row["code"]: row for row in cursor.fetchall()}

    cursor.execute(
        """
        SELECT s.id, s.department_id, s.semester, s.credits
        FROM subjects s
        JOIN departments d ON d.id = s.department_id
        WHERE s.is_active = TRUE
        ORDER BY s.department_id, s.semester, s.code
        """
    )
    subjects_by_dept_sem = {}
    for row in cursor.fetchall():
        subjects_by_dept_sem.setdefault((row["department_id"], row["semester"]), []).append(row)

    student_map = {student["register_no"]: student for student in dataset["students"]}
    inserted_students = 0
    inserted_results = 0

    for student in dataset["students"]:
        dept = departments.get(student["department_code"])
        if not dept:
            raise RuntimeError(f"Department code {student['department_code']} was not found in DB.")

        user_id = ensure_student_user(cursor, student["register_no"], student_role_id)
        cursor.execute(
            """
            INSERT INTO students (
                roll_number, user_id, name, department_id, admission_year, current_semester,
                email, phone, gender, dob, address
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON DUPLICATE KEY UPDATE
                user_id = VALUES(user_id),
                name = VALUES(name),
                department_id = VALUES(department_id),
                admission_year = VALUES(admission_year),
                current_semester = VALUES(current_semester),
                email = VALUES(email),
                phone = VALUES(phone),
                gender = VALUES(gender),
                dob = VALUES(dob),
                address = VALUES(address)
            """,
            (
                student["register_no"],
                user_id,
                student["name"],
                dept["id"],
                student["batch"],
                student["semester"],
                student["email"],
                student["phone"],
                student["gender"],
                student["dob"],
                "Sample dashboard data",
            ),
        )
        inserted_students += 1

    conn.commit()

    for record in dataset["academic_records"]:
        student = student_map[record["student_roll"]]
        dept = departments[student["department_code"]]
        subjects = subjects_by_dept_sem.get((dept["id"], record["semester"]), [])
        if not subjects:
            raise RuntimeError(
                f"No subjects found for {student['department_code']} semester {record['semester']}."
            )

        for subject in subjects:
            internal_marks, external_marks, total_marks, grade, grade_point = build_subject_mark(
                rng, record["sgpa"]
            )
            cursor.execute(
                """
                INSERT INTO semester_results (
                    student_roll, subject_id, academic_year, semester, internal_marks,
                    external_marks, total_marks, grade, grade_point, credits, result
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON DUPLICATE KEY UPDATE
                    internal_marks = VALUES(internal_marks),
                    external_marks = VALUES(external_marks),
                    total_marks = VALUES(total_marks),
                    grade = VALUES(grade),
                    grade_point = VALUES(grade_point),
                    credits = VALUES(credits),
                    result = VALUES(result)
                """,
                (
                    record["student_roll"],
                    subject["id"],
                    record["academic_year"],
                    record["semester"],
                    internal_marks,
                    external_marks,
                    total_marks,
                    grade,
                    grade_point,
                    subject["credits"],
                    "Pass",
                ),
            )
            inserted_results += 1

        if record["id"] % 100 == 0:
            conn.commit()

    conn.commit()
    cursor.close()
    conn.close()

    print(f"Imported {inserted_students} students into students/users.")
    print(f"Imported {inserted_results} subject results into semester_results.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Import dashboard JSON sample data into MySQL.")
    parser.add_argument(
        "--file",
        default=str(DEFAULT_OUTPUT),
        help="Path to the student JSON file. Defaults to student_db_720.json.",
    )
    parser.add_argument(
        "--replace-existing",
        action="store_true",
        help="Delete existing student data before importing the 720-student sample set.",
    )
    args = parser.parse_args()
    import_dataset(Path(args.file), replace_existing=args.replace_existing)
